MCareSite/ViewModels/BankDetailsViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NajmetAlraqee.Site.ViewModels
{
    public class BankDetailViewModels
    {
        [Required]
        public int Id { get; set; }

        [Required(ErrorMessage ="الرجاء أدخال البنك")]
        public string Name { get; set; }

        [Required(ErrorMessage = "الرجاء أدخال رقم الحساب")]
        public string AccountNumber { get; set; }

        [Required(ErrorMessage = "الرجاء أدخال حساب الدليل")]
        public int? AccountTreeId { get; set; }
    }
}

MCareSite/Controllers/BankDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NajmetAlraqee.Data;
using NajmetAlraqee.Data.Entities;
using NajmetAlraqee.Data.Repositories;
using NajmetAlraqee.Site.ViewModels;
using NToastNotify;

namespace NajmetAlraqee.Site.Controllers
{
    [Authorize]
    public class BankDetailsController : Controller
    {
        private readonly NajmetAlraqeeContext _context;
        private readonly IBankDetailRepository _bank;
        private readonly IMapper _mapper;
        private readonly IToastNotification _toastNotification;
        private readonly IAccountTreeRepository _Acctree;

        public BankDetailsController(NajmetAlraqeeContext context,
            IBankDetailRepository bank,
             IAccountTreeRepository Acctree,
            IMapper mapper, 
            IToastNotification toastNotification)
        {
            _context = context;
            _bank = bank;
            _mapper = mapper;
            _Acctree = Acctree;
            _toastNotification = toastNotification;
        }

        #region Index 
        public IActionResult Index(int? page)
        {
            var banks = _bank.GetBankDetails();
            ViewBag.Banks = banks;
            ViewBag.AccountTreeId = new SelectList(_Acctree.GetAccountTrees(), "Id", "DescriptionAr");
            //if (nationality.Count() <= 10) { page = 1; }
            //int pageSize = 10;
            return View();
        }
        #endregion






        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddPost(BankDetailViewModels bankDetailViewModels)
        {
            var banksList = _bank.GetBankDetails();
            ViewBag.Banks = banksList;
            ViewBag.AccountTreeId = new SelectList(_Acctree.GetAccountTrees(), "Id", "DescriptionAr");
            if (bankDetailViewModels.AccountTreeId == null) { ModelState.AddModelError("", "الرجاء تحدد رقم الحساب في الشجرة"); }
            if (bankDetailViewModels.Id == 0)
            {
                ModelState.Remove("Id");
                ModelState.Remove("AccountTreeId");
                if (ModelState.IsValid)
                {
                    var bankdetail = _mapper.Map<BankDetail>(bankDetailViewModels);
                    _bank.AddBankDetail(bankdetail);
                    _toastNotification.AddSuccessToastMessage("تم أضافةالبنك بنجاح");
                    return RedirectToAction(nameof(Index));
                }
                return View(nameof(Index), bankDetailViewModels);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var bankdetail = _mapper.Map<BankDetail>(bankDetailViewModels);
                    _bank.UpdateBankDetail(bankDetailViewModels.Id, bankdetail);
                    _toastNotification.AddSuccessToastMessage("تم تعديل البنك بنجاح");
                    return RedirectToAction(nameof(Index));
                }
                return View(nameof(Index), bankDetailViewModels);
            }

        }


        public IActionResult Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankdetail = _bank.GetBankDetailById((int)id);
            var bankDetailViewModels = _mapper.Map<BankDetailViewModels>(bankdetail);
            if (bankdetail == null)
            {
                return NotFound();
            }
            var banksList = _bank.GetBankDetails();
            ViewBag.AccountTreeId = new SelectList(_Acctree.GetAccountTrees(), "Id", "DescriptionAr", bankdetail.AccountTreeId);
            ViewBag.Banks = banksList;
            return View("Index", bankDetailViewModels);
        }
        #region Delete

        public IActionResult Delete(int id)
        {
            _bank.RemoveBankDetail(id);
            _toastNotification.AddSuccessToastMessage("تم الحذف بنجاح");
            return RedirectToAction(nameof(Index));
        }

        #endregion 


    }
}

MCareSite/Views/BankDetails/Index.cshtml
@model NajmetAlraqee.Site.ViewModels.BankDetailViewModels
@using NajmetAlraqee.Site.Services;
@using NajmetAlraqeeSite.Resources

@inject LocService SharedLocalizer
@{
    ViewData["Title"] = SharedLocalizer.GetLocalizedHtmlString("Banks");
}
@*<script src="~/scripts/toastr.js"></script>
    <script src="~/scripts/toastr.min.js"></script>*@
<div class="block-header">
    <ol class="breadcrumb breadcrumb-col-cyan">
        <li><a href=@Url.Action("index","Home")><i class="material-icons">home</i>@SharedLocalizer.GetLocalizedHtmlString("Home") </a></li>
        <li><a href="javascript:void(0);"><i class="material-icons">library_books</i> @SharedLocalizer.GetLocalizedHtmlString("Banks")</a></li>
    </ol>
</div>


<div class="container-fluid">

    <div class="row clearfix">
        <div class="col-md-12 col-xs-12">
            <div class="card patients-list">
                <div class="body">
                    <h2 class="card-inside-title" style="font-family:Droid Arabic Kufi">@SharedLocalizer.GetLocalizedHtmlString("AddBank")</h2>
                    <div class="row clearfix">
                        <div class="col-sm-12">
                            <form asp-action="AddPost" asp-controller="BankDetails">
                                @Html.AntiForgeryToken()

                                @Html.HiddenFor(x => x.Id)
                                <div class="row">
                                    <div class="col-sm-2 col-xs-12"></div>
                                    <div class="col-sm-8 col-xs-12">
                                        <div asp-validation-summary="All" style="font-family:Droid Arabic Kufi" class="text-danger"></div>
                                        @Html.HiddenFor(x => x.Id)
                                    </div>
                                    <div class="col-sm-2 col-xs-12"></div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input asp-for="Name" class="form-control" style="font-family:Droid Arabic Kufi" placeholder="@SharedLocalizer.GetLocalizedHtmlString("Bank")" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input asp-for="AccountNumber" class="form-control" style="font-family:Droid Arabic Kufi" placeholder="@SharedLocalizer.GetLocalizedHtmlString("AccountNumber")" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <select asp-for="@Model.AccountTreeId" class="form-control" style="font-family:Droid Arabic Kufi" asp-items="ViewBag.AccountTreeId"><option>@SharedLocalizer.GetLocalizedHtmlString("TreeAccountNo")</option></select>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <center>
                                    <input type="submit" style="font-family:Droid Arabic Kufi" value="@SharedLocalizer.GetLocalizedHtmlString("Save")" class="btn btn-raised btn-success btn-sm" />
                                </center>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12 col-xs-12">
            <div class="card patients-list">
                <div class="body">
                    <h2  style="font-family:Droid Arabic Kufi" class="card-inside-title">@SharedLocalizer.GetLocalizedHtmlString("Banks")</h2>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayName(SharedLocalizer.GetLocalizedHtmlString("Code"))
                                    </th>
                                    <th>
                                        @Html.DisplayName(SharedLocalizer.GetLocalizedHtmlString("Bank"))
                                    </th>
                                    <th>
                                        @Html.DisplayName(SharedLocalizer.GetLocalizedHtmlString("AccountNumber"))
                                    </th>
                                    <th>
                                        @Html.DisplayName(SharedLocalizer.GetLocalizedHtmlString("TreeAccountNo"))
                                    </th>
                                    <th>
                                        @Html.DisplayName(SharedLocalizer.GetLocalizedHtmlString("DescriptionAr"))
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (ViewBag.Banks != null)
                                {
                                    @foreach (var item in ViewBag.Banks)
                                    {
                                <tr>
                                    <td>
                                        @item.Id
                                    </td>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td>
                                        @item.AccountNumber
                                    </td>
                                    <td>
                                        @item.AccountTree.AccountNo
                                    </td>
                                    <td>
                                        @item.AccountTree.DescriptionAr
                                    </td>
                                    <td>
                                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-raised btn-secondary btn-sm">@SharedLocalizer.GetLocalizedHtmlString("Edit")</a> |
                                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-raised btn-danger btn-sm">@SharedLocalizer.GetLocalizedHtmlString("Delete")</a>
                                    </td>
                                </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>

@*@{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <a asp-action="Index"
       asp-route-page="@(Model.PageIndex - 1)"
       class="btn btn-default @prevDisabled">
        @SharedLocalizer.GetLocalizedHtmlString("Previous")
    </a>
    <a asp-action="Index"
       asp-route-page="@(Model.PageIndex + 1)"
       class="btn btn-default @nextDisabled">
        @SharedLocalizer.GetLocalizedHtmlString("Next")
    </a>*@

<div class="modal fade" id="defaultModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="defaultModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sodales orci ante, sed ornare eros vestibulum ut. Ut accumsan
                vitae eros sit amet tristique. Nullam scelerisque nunc enim, non dignissim nibh faucibus ullamcorper.
                Fusce pulvinar libero vel ligula iaculis ullamcorper. Integer dapibus, mi ac tempor varius, purus
                nibh mattis erat, vitae porta nunc nisi non tellus. Vivamus mollis ante non massa egestas fringilla.
                Vestibulum egestas consectetur nunc at ultricies. Morbi quis consectetur nunc.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link waves-effect">SAVE CHANGES</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
</div>