MCareSite/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace NajmetAlraqeeSite.Controllers
{
    public class BaseController : Controller
    {
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );
            return LocalRedirect(returnUrl);
        }
    }
}

MCareSite/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using NajmetAlraqee.Data;
using NajmetAlraqee.Data.Entities;
using NajmetAlraqee.Data.Repositories;
using NajmetAlraqee.Site.Services;
using NajmetAlraqee.Site.ViewModels;
using NajmetAlraqeeSite.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace NajmetAlraqeeSite.Controllers
{
    [Authorize]
    public class CitiesController : Controller
    {
        private readonly ICityRepository _city;
        private readonly ICountryRepository _country;
        private readonly IMapper  _mapper;
        private readonly IToastNotification _toastNotification;

        public CitiesController(ICityRepository city, IToastNotification toastNotification, IMapper mapper , ICountryRepository country )
        {
            _city = city;
            _mapper = mapper;
            _country = country;
            _toastNotification = toastNotification;
        }
       
        #region Index 
        public IActionResult Index(int? page)
        {
            var cityList = _city.GetCities();
            ViewBag.Cities = cityList;
            ViewBag.CountryId = new SelectList(_country.GetCountries(), "Id", "Name");
            return View();
        }
        #endregion




        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.CountryId = new SelectList(_country.GetCountries(), "Id", "Name");
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult AddPost(CityViewModel cityViewModel)
        {
            ViewBag.CountryId = new SelectList(_country.GetCountries(), "Id", "Name");
            var cityList = _city.GetCities();
            ViewBag.Cities = cityList;
            if (cityViewModel.CountryId == null) { ModelState.AddModelError("", "الرجاء ادخال البلد"); }
            if (cityViewModel.Id == 0)
            {
                ModelState.Remove("Id");
                ModelState.Remove("CountryId");
                if (ModelState.IsValid)
                {
                    var city = _mapper.Map<City>(cityViewModel);
                    _city.AddCity(city);
                    _toastNotification.AddSuccessToastMessage("تم أضافةالمدينة بنجاح");
                    return RedirectToAction(nameof(Index));
                }
                return View(nameof(Index), cityViewModel);
            }
            else
            {
                ModelState.Remove("CountryId");
                if (ModelState.IsValid)
                {
                    var city = _mapper.Map<City>(cityViewModel);
                    _city.UpdateCity(cityViewModel.Id, city);
                    _toastNotification.AddSuccessToastMessage("تم تعديل المدينة بنجاح");
                    return RedirectToAction(nameof(Index));
                }
                return View(nameof(Index), cityViewModel);
            }
        }

        public IActionResult Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.CountryId = new SelectList(_country.GetCountries(), "Id", "Name");
            var city = _city.GetCityById((int)id);
            var cityViewModel = _mapper.Map<CityViewModel>(city);
            if (city == null)
            {
                return NotFound();
            }
            var cityList = _city.GetCities();
            ViewBag.Cities = cityList;
            return View("Index", cityViewModel);
        }

        //#region Delete

        public IActionResult Delete(int id)
        {
            _city.RemoveCity(id);
            _toastNotification.AddSuccessToastMessage("تم الحذف بنجاح");
            return RedirectToAction(nameof(Index));
        }

        //#endregion



    }
}

MCareSite/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FastReport.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using NajmetAlraqee.Data.Repositories;
using NToastNotify;

namespace NajmetAlraqee.Site.Controllers
{   [Authorize]
    public class ReportController : Controller
    {
        #region Filed
        private readonly IAccountClassificationRepository _AccClassification;
        private readonly IAccountClassificationTypeRepository _Acctype;
        private readonly IMapper _mapper;
        private readonly IAccountTreeRepository _tree;
        private readonly IHostingEnvironment _hostingEnvironment;
        public readonly IConfiguration _configuration;
        public WebReport webReport = new WebReport();
        #endregion

        public ReportController(
         IMapper mapper,  IHostingEnvironment hostingEnvironment,
         IAccountClassificationTypeRepository acctype, IAccountClassificationRepository accClassification,
         IAccountTreeRepository tree , IConfiguration configuration)
        {
            _mapper = mapper;
            _AccClassification = accClassification;
            _Acctype = acctype;
            _tree = tree;
            _hostingEnvironment = hostingEnvironment;
            _configuration = configuration;
        }

        #region AccountTreeReport 
        public IActionResult AccountTreeIndex(int accountLevel, string accName , string accNo)
        {
            if (accountLevel>0 || accName!= null || accNo!= null ) {
                SetReportAccountTree(accountLevel, accName, accNo);
            }
            else {
                SetReportAccountTree();
            }
            return View(webReport);
        }
        private void SetReportAccountTree(int accountLevel, string accName, string accNo)
        {
            var webRoot = _hostingEnvironment.WebRootPath + "\\Reporting\\AccountTree\\";
            webReport.Width = "1000"; // Set the width of the report
            webReport.Height = "1000"; // Set the height of the report
            var file = Path.Combine(webRoot, "AccountTreeFilterReport.frx");
            string report_path = file;
            var connection = _configuration.GetConnectionString("DefaultConnection");
            MsSqlDataConnection sqlConnection = new MsSqlDataConnection
            {
                ConnectionString = _configuration.GetConnectionString("DefaultConnection")
            };
            sqlConnection.CreateAllTables();
            webReport.Report.Dictionary.Connections.Add(sqlConnection);
            webReport.Report.Load(file);
            webReport.Report.SetParameterValue("AccountLevel", accountLevel);
            webReport.Report.SetParameterValue("AccountName", accName);
            webReport.Report.Prepare();
        }
        private void SetReportAccountTree()
        {
            var webRoot = _hostingEnvironment.WebRootPath + "\\Reporting\\AccountTree\\";
            webReport.Width = "1000"; // Set the width of the report
            webReport.Height = "1000"; // Set the height of the report
            var file = Path.Combine(webRoot, "AccountTreeReport.frx");
            string report_path = file;
            MsSqlDataConnection sqlConnection = new MsSqlDataConnection
            {
                ConnectionString = _configuration.GetConnectionString("DefaultConnection")
        };
            sqlConnection.CreateAllTables();
            webReport.Report.Dictionary.Connections.Add(sqlConnection);
            webReport.Report.Load(file);
        }
        #endregion

        #region ContractReport 
        public IActionResult ContractIndex(string FromDate, string ToDate, string Country , int LateDate,string ForiegnAgency)
        {
            if ( FromDate!= null || ToDate != null ||Country != null || LateDate > 0 || ForiegnAgency != null)
            {
                SetReportContract(FromDate, ToDate, Country, LateDate, ForiegnAgency);
            }
            else
            {
                SetReportContract();
            }
            return View(webReport);
        }
        private void SetReportContract(string FromDate, string ToDate, string Country, int LateDate, string ForiegnAgency)
        {
            var webRoot = _hostingEnvironment.WebRootPath + "\\Reporting\\Contracts\\";
            webReport.Width = "1000"; // Set the width of the report
            webReport.Height = "1000"; // Set the height of the report
            var file = Path.Combine(webRoot, "ContractFilterReport.frx");
            string report_path = file;
            MsSqlDataConnection sqlConnection = new MsSqlDataConnection
            {
                ConnectionString = _configuration.GetConnectionString("DefaultConnection")
            };
            sqlConnection.CreateAllTables();
            webReport.Report.Dictionary.Connections.Add(sqlConnection);
            webReport.Report.Load(file);
            //webReport.Report.SetParameterValue("FromDate", FromDate);
            //webReport.Report.SetParameterValue("ToDate", ToDate);
            webReport.Report.SetParameterValue("Country", Country);
            webReport.Report.SetParameterValue("LateDate", LateDate);
            webReport.Report.SetParameterValue("ForiegnAgency", ForiegnAgency);
            webReport.Report.Prepare();
        }
        private void SetReportContract()
        {
            var webRoot = _hostingEnvironment.WebRootPath + "\\Reporting\\Contracts\\";
            webReport.Width = "1000"; // Set the width of the report
            webReport.Height = "1000"; // Set the height of the report
            var file = Path.Combine(webRoot, "ContractReport.frx");
            string report_path = file;
            MsSqlDataConnection sqlConnection = new MsSqlDataConnection
            {
                ConnectionString = _configuration.GetConnectionString("DefaultConnection")
            };
            sqlConnection.CreateAllTables();
            webReport.Report.Dictionary.Connections.Add(sqlConnection);
            webReport.Report.Load(file);
        }
        #endregion 


    }
}

MCareSite/Views/Shared/SideMenu.cshtml
@using NajmetAlraqeeSite.Resources

@inject LocService SharedLocalizer
@*<nav class="navbar clearHeader">
        <div class="navbar-header"> <a href="javascript:void(0);" class="bars"></a> <a class="navbar-brand" href="index.html"><img class="logo" src="~/themeforest/HTML/assets/images/logo.svg" alt="profile img">Hospital</a> </div>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="zmdi zmdi-search"></i></a></li>
            <a href="@Url.Action("SetLanguage","Base",new { culture="ar" , returnUrl=Context.Request.Path })"><img title="Arabic" src="~/images/sa.jpg"></a>
            &nbsp; &nbsp;
            <a href="@Url.Action("SetLanguage","Base",new { culture="en-US",  returnUrl=Context.Request.Path})"><img src="~/images/us.jpg" title="English"></a>
            <li><a href="sign-in.html" class="mega-menu" data-close="true"><i class="zmdi zmdi-power"></i></a></li>
            <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="zmdi zmdi-sort-amount-desc"></i></a></li>
        </ul>
    </nav>*@

<!-- Left Sidebar -->
<aside id="leftsidebar" class="sidebar">
    <!-- Menu -->
    <div class="menu" style="font-family:Droid Arabic Kufi">
        <ul class="list">
            <li>
                <div class="user-info">
                    <div class="admin-image"> <img src="~/images/MainLOG.jpg" alt="profile img"> </div>
                    <div class="admin-action-info">
                        <span>@SharedLocalizer.GetLocalizedHtmlString("Welcome")</span>
                        <h3>@User.Identity.Name</h3>
                    </div>
                </div>
            </li>
            <li class="header">@SharedLocalizer.GetLocalizedHtmlString("MAINNAVIGATION")</li>


            @*@if (User.IsInRole("Administrator"))*@
            @*{*@

            @if (User.IsInRole("ADMIN"))
            {
                <li><a asp-action="Index" asp-controller="DashBoards"> <i class="zmdi zmdi-home"></i><span>@SharedLocalizer.GetLocalizedHtmlString("Dashboard")</span></a></li>
            }

            @if (User.IsInRole("ADMIN") || User.IsInRole("SUPERUSER") || User.IsInRole("USEREMP"))
            {
                <li>
                    <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-pin-account"></i><span>@SharedLocalizer.GetLocalizedHtmlString("Customers")</span></a>
                    <ul class="ml-menu">
                        <li><a asp-action="Index" asp-controller="Customer">@SharedLocalizer.GetLocalizedHtmlString("Customers")</a></li>
                        <li><a asp-action="Add" asp-controller="Customer">@SharedLocalizer.GetLocalizedHtmlString("AddCustomer")</a></li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-pin-account"></i><span>@SharedLocalizer.GetLocalizedHtmlString("Contracts")</span></a>
                    <ul class="ml-menu">
                        <li><a asp-action="Index" asp-controller="Contract">@SharedLocalizer.GetLocalizedHtmlString("Contracts")</a></li>
                        <li><a asp-action="Add" asp-controller="Contract" asp-route-contractType="1">@SharedLocalizer.GetLocalizedHtmlString("AddContract")</a></li>
                        <li><a asp-action="Index" asp-controller="SpecificContracts">@SharedLocalizer.GetLocalizedHtmlString("SpecificContracts")</a></li>
                        <li><a asp-action="Index" asp-controller="ContractReturn">@SharedLocalizer.GetLocalizedHtmlString("ContractReturns")</a></li>
                        <li><a asp-action="Index" asp-controller="Invoice">@SharedLocalizer.GetLocalizedHtmlString("Invoices")</a></li>
                    </ul>
                </li>

            }

            @if (User.IsInRole("ADMIN"))
            {
                <li>
                    <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-reader"></i><span>@SharedLocalizer.GetLocalizedHtmlString("SnadReceipts")</span></a>
                    <ul class="ml-menu">
                        <li><a asp-action="Index" asp-controller="SnadReceipt">@SharedLocalizer.GetLocalizedHtmlString("SnadReceipts")</a></li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-reader"></i><span>قائمة التحويلات </span></a>
                    <ul class="ml-menu">
                        <li><a asp-action="Index" asp-controller="ForeignAgencyTransfer">@SharedLocalizer.GetLocalizedHtmlString("ForeignAgencyTransfers")</a></li>
                        <li><a asp-action="Index" asp-controller="UserDelegateTransfers">@SharedLocalizer.GetLocalizedHtmlString("DelegateTransfers")</a></li>
                    </ul>
                </li>
            }
            @if (User.IsInRole("ADMIN"))
            {
                <li>
                    <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-settings"></i><span>@SharedLocalizer.GetLocalizedHtmlString("Financ")</span> </a>
                    <ul class="ml-menu">
                        <li><a asp-action="Index" asp-controller="AccountTree">@SharedLocalizer.GetLocalizedHtmlString("AccountTrees")</a></li>
                        <li><a asp-action="Index" asp-controller="FinancialPeriod">@SharedLocalizer.GetLocalizedHtmlString("FinancialPeriods")</a></li>
                        <li><a asp-action="Index" asp-controller="AccountClassification">@SharedLocalizer.GetLocalizedHtmlString("AccountClassifications")</a></li>
                        <li><a asp-action="Index" asp-controller="RecruitmentQaid">@SharedLocalizer.GetLocalizedHtmlString("RecruitmentQaids")</a></li>
                    </ul>
                </li>
            }
            @if (User.IsInRole("ADMIN"))
            {
                <li>
                    <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-accounts"></i><span>@SharedLocalizer.GetLocalizedHtmlString("Company")</span> </a>
                    <ul class="ml-menu">
                        <li> <a asp-action="Index" asp-controller="Users">@SharedLocalizer.GetLocalizedHtmlString("Users")</a></li>
                        @*<li> <a asp-action="Add" asp-controller="Users">@SharedLocalizer.GetLocalizedHtmlString("AddUser")</a></li>*@
                        <li> <a asp-action="Index" asp-controller="ApplicationRoles">@SharedLocalizer.GetLocalizedHtmlString("Roles")</a></li>
                        <li><a asp-action="Index" asp-controller="Employee">@SharedLocalizer.GetLocalizedHtmlString("Employees")</a></li>
                        <li><a asp-action="Index" asp-controller="SpecialEmployee">@SharedLocalizer.GetLocalizedHtmlString("SpecialEmployees")</a></li>
                        <li><a asp-action="Index" asp-controller="ForeginAgencies">@SharedLocalizer.GetLocalizedHtmlString("ForeignAgencies")</a></li>
                        <li><a asp-action="Index" asp-controller="Delegates">@SharedLocalizer.GetLocalizedHtmlString("Delegates")</a></li>
                        <li><a asp-action="Index" asp-controller="Partner">@SharedLocalizer.GetLocalizedHtmlString("Partners")</a></li>
                    </ul>
                </li>
            }
            @if (User.IsInRole("ADMIN"))
            {
                <li>
                    <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-settings"></i><span>@SharedLocalizer.GetLocalizedHtmlString("Setting")</span> </a>
                    <ul class="ml-menu">
                        <li><a asp-action="Index" asp-controller="BankDetails">@SharedLocalizer.GetLocalizedHtmlString("Banks")</a></li>
                        <li><a asp-action="Index" asp-controller="Expenses">@SharedLocalizer.GetLocalizedHtmlString("Expenses")</a></li>
                        <li><a asp-action="Index" asp-controller="JobTypes">@SharedLocalizer.GetLocalizedHtmlString("JobTypes")</a></li>
                        <li><a asp-action="Index" asp-controller="Currencies">@SharedLocalizer.GetLocalizedHtmlString("Currencies")</a></li>
                        <li><a asp-action="Index" asp-controller="Nationalities">@SharedLocalizer.GetLocalizedHtmlString("Nationalities")</a></li>
                        <li><a asp-action="Index" asp-controller="Arrival">@SharedLocalizer.GetLocalizedHtmlString("Arrivals")</a></li>
                        <li><a asp-action="Index" asp-controller="PaymentMethod">@SharedLocalizer.GetLocalizedHtmlString("PaymentMethods")</a></li>
                        <li><a asp-action="Index" asp-controller="Countries">@SharedLocalizer.GetLocalizedHtmlString("Countries")</a></li>
                        <li><a asp-action="Index" asp-controller="Cities">@SharedLocalizer.GetLocalizedHtmlString("Cities")</a></li>
                    </ul>
                </li>
            }
            @if (User.IsInRole("ADMIN"))
            {
                <li>
                    <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-settings"></i><span>@SharedLocalizer.GetLocalizedHtmlString("Reports")</span> </a>
                    <ul class="ml-menu">
                        <li><a asp-action="AccountTreeIndex" asp-controller="Report">@SharedLocalizer.GetLocalizedHtmlString("AccountTreeReport")</a></li>
                        <li><a asp-action="ContractIndex" asp-controller="Report">@SharedLocalizer.GetLocalizedHtmlString("Contracts")</a></li>
                    </ul>
                </li>
            }
        </ul>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane in active" id="settings">
                <div class="slim-scroll">
                    <div class="card">
                        <div class="header">
                            <h2>@SharedLocalizer.GetLocalizedHtmlString("ColorOPTIONS")</h2>
                        </div>
                        <div class="body">
                            <ul class="choose-skin m-b-0">
                                <li data-theme="purple">
                                    <div class="purple"></div>
                                </li>
                                <li data-theme="blue">
                                    <div class="blue"></div>
                                </li>
                                <li data-theme="cyan" class="active">
                                    <div class="cyan"></div>
                                </li>
                                <li data-theme="green">
                                    <div class="green"></div>
                                </li>
                                <li data-theme="blush">
                                    <div class="blush"></div>
                                </li>
                            </ul>
                            <ul class="list-unstyled m-b-0 theme-light-dark m-t-15">
                                <li>
                                    <div class="t-dark">Dark</div>
                                </li>
                                <li>
                                    <div class="t-light">Light</div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</aside>

MCareSite/Views/Shared/_SelectLanguagePartial.cshtml
@using System.Threading.Tasks
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home"
          asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
          method="post" class="form-horizontal" role="form">
        @Localizer["Language:"] <select name="culture"
                                        asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
        <button type="submit" class="btn btn-default btn-xs">Save</button>
    </form>
</div>  