MCareSite/ViewModels/RecruitmentQaidDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NajmetAlraqee.Site.ViewModels
{
    public class RecruitmentQaidDetailViewModel
    {
        public int Id { get; set; }

        public int? QaidId { get; set; }

        [Required(ErrorMessage =" الرجاء تحديد نوع بند القيد")]
        public int? TypeId { get; set; }

        [Required(ErrorMessage = " الرجاء تحديد الحساب ")]
        public int? AccountTreeId { get; set; }

        public decimal? Credit { get; set; }

        public decimal? Debit { get; set; }

        [Required(ErrorMessage = " الرجاءادخال الملاحظة")]
        public string Note { get; set; }
    }
}

MCareSite/Controllers/RecruitmentQaidDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NajmetAlraqee.Data.Entities;
using NajmetAlraqee.Data.Repositories;
using NajmetAlraqee.Site.ViewModels;
using NToastNotify;

namespace NajmetAlraqee.Site.Controllers
{
    [Authorize]
    public class RecruitmentQaidDetailController : Controller
    {
        #region Filed 
        private readonly IAccountTreeRepository _accTree;
        private readonly IRecruitmentQaidRepository _qaid;
        private readonly IRecruitmentQaidDetailRepository _qaidDetail;
        private readonly IMapper _mapper;
        private readonly IToastNotification _toastNotification;
        private readonly IRecruitmentQaidDetailTypeRepository _detailType;
        #endregion

        public RecruitmentQaidDetailController(IAccountTreeRepository accTree,
            IMapper mapper, IRecruitmentQaidRepository qaid,
            IToastNotification toastNotification
            , IRecruitmentQaidDetailTypeRepository detailType ,
            IRecruitmentQaidDetailRepository qaidDetail)
        {
            _accTree = accTree;
            _mapper = mapper;
            _toastNotification = toastNotification;
            _qaid = qaid;
            _detailType = detailType;
            _qaidDetail = qaidDetail;
        }



        #region Index 
        public IActionResult Index(int? page, string SearchString, int? RecruitmentQaidId, int? Id)
        {

            RecruitmentQaidDetailViewModel detail = new RecruitmentQaidDetailViewModel
            {
                QaidId = RecruitmentQaidId,
            };

            if (Id != null)
            {
                var qaidDetail = _qaidDetail.GetRecruitmentQaidDetailById((int)Id);
                var qaidDetailViewModels = _mapper.Map<RecruitmentQaidDetailViewModel>(qaidDetail);
                detail.AccountTreeId = qaidDetailViewModels.AccountTreeId;
                detail.TypeId = qaidDetailViewModels.TypeId;
                detail.Debit = qaidDetailViewModels.Debit;
                detail.Credit = qaidDetailViewModels.Credit;
                detail.Note = qaidDetailViewModels.Note;
            }


            var qaidDetailList = _qaidDetail.GetRecruitmentQaidDetails().Where(x => x.QaidId == RecruitmentQaidId);
            ViewBag.QaidDetail = qaidDetailList;

            ViewBag.AccountTreeId = new SelectList(_accTree.GetAccountTrees(), "Id", "DescriptionAr");
            ViewBag.TypeId = new SelectList(_detailType.GetRecruitmentQaidDetailTypes(), "Id", "Name");
            return View(detail);
        }
        #endregion


        #region Add

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.AccountTreeId = new SelectList(_accTree.GetAccountTrees(), "Id", "DescriptionAr");
            ViewBag.TypeId = new SelectList(_detailType.GetRecruitmentQaidDetailTypes(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(RecruitmentQaidDetailViewModel qaidDetailViewModels)
        {
            ViewBag.AccountTreeId = new SelectList(_accTree.GetAccountTrees(), "Id", "DescriptionAr");
            ViewBag.TypeId = new SelectList(_detailType.GetRecruitmentQaidDetailTypes(), "Id", "Name");
            if (qaidDetailViewModels.AccountTreeId == null) { ModelState.AddModelError("", "الرجاء تحديد الحساب"); }
            if (qaidDetailViewModels.TypeId == null) { ModelState.AddModelError("", "الرجاء نوع بند القيد "); }
            if (qaidDetailViewModels.Id == 0)
            {
                ModelState.Remove("Id");
                ModelState.Remove("AccountTreeId");
                ModelState.Remove("TypeId");
               
                if (ModelState.IsValid)
                {
                    var qaidDetail = _mapper.Map<RecruitmentQaidDetail>(qaidDetailViewModels);
                    _qaidDetail.AddRecruitmentQaidDetail(qaidDetail);
                    _toastNotification.AddSuccessToastMessage("تم أضافة بند للقيد بنجاح");
                    return RedirectToAction(nameof(Index), new { RecruitmentQaidId = qaidDetailViewModels.QaidId });
                }
                return View(nameof(Index), qaidDetailViewModels);
            }
            else
            {
                ModelState.Remove("AccountTreeId");
                ModelState.Remove("TypeId");

                if (ModelState.IsValid)
                {
                    var qaidDetail = _mapper.Map<RecruitmentQaidDetail>(qaidDetailViewModels);
                    _qaidDetail.UpdateRecruitmentQaidDetail(qaidDetailViewModels.Id, qaidDetail);
                    _toastNotification.AddSuccessToastMessage("تم تعديل  بند للقيد بنجاح");
                    return RedirectToAction(nameof(Index), new { RecruitmentQaidId = qaidDetailViewModels.QaidId });
                }
                return View(nameof(Index), qaidDetailViewModels);
            }

        }

        #endregion

    }
}

MCareSite/Views/RecruitmentQaidDetail/Index.cshtml
@model NajmetAlraqee.Site.ViewModels.RecruitmentQaidDetailViewModel
@using NajmetAlraqee.Site.Services;
@using NajmetAlraqeeSite.Resources

@inject LocService SharedLocalizer
@{
    ViewData["Title"] = SharedLocalizer.GetLocalizedHtmlString("RecruitmentQaids");
}

<div class="block-header">
    <ol class="breadcrumb breadcrumb-col-cyan">
        <li><a href=@Url.Action("index","Home")><i class="material-icons">home</i>@SharedLocalizer.GetLocalizedHtmlString("Home") </a></li>
        <li><a href="javascript:void(0);"><i class="material-icons">library_books</i> @SharedLocalizer.GetLocalizedHtmlString("RecruitmentQaids")</a></li>
    </ol>
</div>

<div class="container-fluid">
    <div class="row clearfix" style="font-family:Droid Arabic Kufi">
        <div class="col-md-12 col-xs-12">
            <div class="card patients-list">
                <div class="body">
                    @*<h2 class="card-inside-title" style="font-family:Droid Arabic Kufi">@SharedLocalizer.GetLocalizedHtmlString("RecruitmentQaids")</h2>*@
                    <div class="row clearfix">
                        <div class="col-sm-12">
                            <form asp-action="Add" method="post" asp-controller="RecruitmentQaidDetail">
                                @Html.HiddenFor(x => x.Id)
                                <div class="row">
                                    <div class="col-sm-2 col-xs-12"></div>
                                    <div class="col-sm-8 col-xs-12">
                                        <div asp-validation-summary="All" style="font-family:Droid Arabic Kufi" class="text-danger"></div>
                                        @Html.HiddenFor(x => x.QaidId)
                                    </div>
                                    <div class="col-sm-2 col-xs-12"></div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label style="color:black">@SharedLocalizer.GetLocalizedHtmlString("AccountNo") </label>
                                            <div class="form-line">
                                                <select asp-for="AccountTreeId" class="form-control" style="font-family:Droid Arabic Kufi" asp-items="ViewBag.AccountTreeId"><option>@SharedLocalizer.GetLocalizedHtmlString("AccountNo")</option></select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label style="color:black">@SharedLocalizer.GetLocalizedHtmlString("QaidType") </label>
                                            <div class="form-line">
                                                <select asp-for="TypeId" class="custom-select form-control" style="font-family:Droid Arabic Kufi" asp-items="ViewBag.TypeId"><option>@SharedLocalizer.GetLocalizedHtmlString("ReturnReason")</option></select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-3 col-xs-12" id="DebitX">
                                        <div class="form-group">
                                            <label style="color:black">@SharedLocalizer.GetLocalizedHtmlString("Debit") </label>
                                            <div class="form-line">
                                                <input asp-for="Debit" class="form-control" style="font-family:Droid Arabic Kufi" placeholder="Debit" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 col-xs-12" id="CreditX">
                                        <div class="form-group">
                                            <label style="color:black">@SharedLocalizer.GetLocalizedHtmlString("Credit") </label>
                                            <div class="form-line">
                                                <input asp-for="Credit" class="form-control" style="font-family:Droid Arabic Kufi" placeholder="Credit" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label style="color:black">@SharedLocalizer.GetLocalizedHtmlString("Note") </label>
                                            <div class="form-line">
                                                <input asp-for="@Model.Note" class="form-control" style="font-family:Droid Arabic Kufi" placeholder="@SharedLocalizer.GetLocalizedHtmlString("Note")" />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <center>
                                    <input type="submit" style="font-family:Droid Arabic Kufi;" value="@SharedLocalizer.GetLocalizedHtmlString("Save")" class="btn btn-raised bg-teal btn-sm" />
                                </center>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row clearfix">
        <div class="col-md-12 col-xs-12">
            <div class="card patients-list">
                <div class="body">
                    <h2 class="card-inside-title" style="font-family:Droid Arabic Kufi">@SharedLocalizer.GetLocalizedHtmlString("RecruitmentQaids")</h2>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayName(SharedLocalizer.GetLocalizedHtmlString("No"))
                                    </th>
                                    <th>
                                        @Html.DisplayName(SharedLocalizer.GetLocalizedHtmlString("AccountNo"))
                                    </th>
                                    <th>
                                        @Html.DisplayName(SharedLocalizer.GetLocalizedHtmlString("QaidType"))
                                    </th>
                                    <th>
                                        @Html.DisplayName("Debit")
                                    </th>
                                    <th>
                                        @Html.DisplayName("Credit")
                                    </th>
                                    <th>
                                        @Html.DisplayName(SharedLocalizer.GetLocalizedHtmlString("Note"))
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (ViewBag.QaidDetail != null)
                                {
                                    @foreach (var item in ViewBag.QaidDetail)
                                    {
                                        <tr>
                                            <td>
                                                @item.Id
                                            </td>
                                            <td>
                                                <label class="label bg-teal">  @item.AccountTree.DescriptionAr </label>
                                            </td>
                                            <td>
                                                <label class="label bg-teal">  @item.Type.Name </label>
                                            </td>
                                            <td>
                                                @item.Debit
                                            </td>
                                            <td>
                                                @item.Credit
                                            </td>
                                            <td>
                                                @item.Note
                                            </td>
                                            @*<td>
                                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-raised bg-teal btn-sm"><i class="material-icons" title="@SharedLocalizer.GetLocalizedHtmlString("Edit")">create</i></a>
                                            </td>*@
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-sm-12">
                    <a asp-action="Details" asp-controller="RecruitmentQaid" asp-route-id="@Model.QaidId" class="btn btn-raised" style="font-family:Droid Arabic Kufi;right:500px">@SharedLocalizer.GetLocalizedHtmlString("Close")</a>
                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    <script src='~/js/jquery-customselect.js'></script>
    <script>
      

        if ($("#TypeId").val() == 1) {
            $("#CreditX").fadeIn('slow');
        } else { $("#CreditX").fadeOut('slow'); }

        if ($("#TypeId").val() == 2) {
            $("#DebitX").fadeIn('slow');
        } else { $("#DebitX").fadeOut('slow'); }

     
        $("#TypeId").change(function () {
            if ($("#TypeId").val() == 1) {
                $("#CreditX").fadeIn('slow');
            } else { $("#CreditX").fadeOut('slow'); }
            if ($("#TypeId").val() == 2) {
                $("#DebitX").fadeIn('slow');
            } else { $("#DebitX").fadeOut('slow'); }
            
        });
    </script>

}